### ISSUE TITLE
Change Nginx static directory

### ISSUE THREAD

**Issue by dongyuzheng** [emerjhack/website#19]
restart.sh now uses collectstatic properly and copies the files to (below)

Please make it point to - /var/www/emerjhack.com/static

Note: You still need to perform - git pull origin dev - before running restart.sh

I tried doing this myself but couldn't find the Nginx config you were using ...

**Comment by dongyuzheng** [comment]
- This fixes css for /admin

**Comment by jyang0** [comment]
Modified your script slightly, also temporarily reset MEDIA_ROOT in settings.py (previous value is invalid), configured nginx.
